name: Node CI

on:
  release:
    types: published
  push:
    branches:
      - '*'

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: |
        npm install
        npm run lint:all
        npm run test
      env:
        CI: true
    - run: npm version $(echo $GITHUB_REF | cut -f3 -d/) --git-tag-version=false && npm publish
      if: contains(github.ref, '/tags/')
      env:
        NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
